// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9DgQs0g5WbFhcFfx9YU2p3iMd3zGmplc',
    appId: '1:53989677370:web:962a5ef1a26d5d8ae5d803',
    messagingSenderId: '53989677370',
    projectId: 'hazard-reporting-app-1',
    authDomain: 'hazard-reporting-app-1.firebaseapp.com',
    storageBucket: 'hazard-reporting-app-1.appspot.com',
    measurementId: 'G-1W5PLPEV76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7FWOSPE74--0KvJjtKVWp4lwo3BUFv4',
    appId: '1:53989677370:android:f1d283e6e65c60ebe5d803',
    messagingSenderId: '53989677370',
    projectId: 'hazard-reporting-app-1',
    storageBucket: 'hazard-reporting-app-1.appspot.com',
  );

}